# Generated by Django 4.2.6 on 2023-10-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_memory', models.CharField(max_length=512)),
                ('cpu_model', models.CharField(max_length=512)),
                ('os', models.CharField(max_length=512)),
                ('disk_space', models.CharField(max_length=512)),
                ('hostname', models.CharField(max_length=512)),
                ('MACs', models.CharField(max_length=512)),
                ('users', models.CharField(max_length=512)),
                ('available_memory', models.CharField(max_length=512)),
                ('disk_usage', models.CharField(max_length=512)),
                ('IPs', models.CharField(max_length=512)),
                ('kernel', models.CharField(max_length=512)),
                ('free_space', models.CharField(max_length=512)),
                ('open_ports', models.CharField(max_length=512)),
            ],
        ),
    ]
